// Dad Jokes ower 100
const dadJokesArr = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them!",
  "I used to hate facial hair, but then it grew on me.",
  "Why don't skeletons fight each other? They don't have the guts!",
  "What's brown and sticky? A stick!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why did the bicycle fall over? It was two-tired!",
  "I'm friends with 25 letters of the alphabet. I don't know why.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "What's the best thing about Switzerland? I don't know, but their flag is a big plus!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the stadium get hot after the game? All of the fans left.",
  "What do you call a snowman with a six-pack? An abdominal snowman!",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "How does a penguin build its house? Igloos it together!",
  "I got a job at a bakery because I kneaded dough.",
  "Why don't skeletons fight each other? They don't have the guts!",
  "I went to buy some camouflage trousers, but I couldn't find any.",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the math book look sad? Because it had too many problems.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "What do you call fake spaghetti? An impasta!",
  "Why did the coffee file a police report? It got mugged!",
  "I wouldn't buy anything with velcro. It's a total rip-off!",
  "How do you organize a space party? You planet!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
  "I used to be a baker, but I couldn't make enough dough.",
  "I'm on a seafood diet. I see food and I eat it!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a pile of cats? A meowtain!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Why did the bicycle fall over? It was two-tired!",
  "I'm friends with 25 letters of the alphabet. I don't know why.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "How do you organize a space party? You planet!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a pile of cats? A meowtain!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "How does a penguin build its house? Igloos it together!",
  "I got a job at a bakery because I kneaded dough.",
  "Why don't skeletons fight each other? They don't have the guts!",
  "I went to buy some camouflage trousers, but I couldn't find any.",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the math book look sad? Because it had too many problems.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "What do you call fake spaghetti? An impasta!",
  "Why did the coffee file a police report? It got mugged!",
  "I wouldn't buy anything with velcro. It's a total rip-off!",
  "Why did the bicycle fall over? It was two-tired!",
  "I'm friends with 25 letters of the alphabet. I don't know why.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "How do you organize a space party? You planet!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
  "I used to be a baker, but I couldn't make enough dough.",
  "I'm on a seafood diet. I see food and I eat it!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a pile of cats? A meowtain!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Why did the bicycle fall over? It was two-tired!",
  "I'm friends with 25 letters of the alphabet. I don't know why.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "How do you organize a space party? You planet!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a pile of cats? A meowtain!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "How does a penguin build its house? Igloos it together!",
  "I got a job at a bakery because I kneaded dough.",
  "Why don't skeletons fight each other? They don't have the guts!",
  "I went to buy some camouflage trousers, but I couldn't find any.",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the math book look sad? Because it had too many problems.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "What do you call fake spaghetti? An impasta!",
  "Why did the coffee file a police report? It got mugged!",
  "I wouldn't buy anything with velcro. It's a total rip-off!",
  "How do you organize a space party? You planet!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
  "I used to be a baker, but I couldn't make enough dough.",
  "I'm on a seafood diet. I see food and I eat it!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a pile of cats? A meowtain!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Why did the bicycle fall over? It was two-tired!",
  "I'm friends with 25 letters of the alphabet. I don't know why.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "How do you organize a space party? You planet!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a pile of cats? A meowtain!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "How does a penguin build its house? Igloos it together!",
  "I got a job at a bakery because I kneaded dough.",
  "Why don't skeletons fight each other? They don't have the guts!",
  "I went to buy some camouflage trousers, but I couldn't find any.",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the math book look sad? Because it had too many problems.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "What do you call fake spaghetti? An impasta!",
  "Why did the coffee file a police report? It got mugged!",
  "I wouldn't buy anything with velcro. It's a total rip-off!",
  "How do you organize a space party? You planet!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
  "I used to be a baker, but I couldn't make enough dough.",
  "I'm on a seafood diet. I see food and I eat it!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a pile of cats? A meowtain!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Why did the bicycle fall over? It was two-tired!",
  "I'm friends with 25 letters of the alphabet. I don't know why.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "How do you organize a space party? You planet!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a pile of cats? A meowtain!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "How does a penguin build its house? Igloos it together!",
  "I got a job at a bakery because I kneaded dough.",
  "Why don't skeletons fight each other? They don't have the guts!",
  "I went to buy some camouflage trousers, but I couldn't find any.",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the math book look sad? Because it had too many problems.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "What do you call fake spaghetti? An impasta!",
  "Why did the coffee file a police report? It got mugged!",
  "I wouldn't buy anything with velcro. It's a total rip-off!",
  "How do you organize a space party? You planet!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
  "I used to be a baker, but I couldn't make enough dough.",
  "I'm on a seafood diet. I see food and I eat it!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a pile of cats? A meowtain!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Why did the bicycle fall over? It was two-tired!",
  "I'm friends with 25 letters of the alphabet. I don't know why.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "How do you organize a space party? You planet!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a pile of cats? A meowtain!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "How does a penguin build its house? Igloos it together!",
  "I got a job at a bakery because I kneaded dough.",
  "Why don't skeletons fight each other? They don't have the guts!",
  "I went to buy some camouflage trousers, but I couldn't find any.",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why did the math book look sad? Because it had too many problems!",
  "Why don't eggs tell jokes? Because they might crack up!",
];

let btn = document.getElementById("joke-button");
let jokeDisplay = document.getElementById("joke-display");

function generateDadJokes() {
  const index = Math.floor(Math.random() * dadJokesArr.length);
  const randomJoke = dadJokesArr[index];
  return randomJoke;
}

jokeDisplay.style.transition = "opacity 0.3s ease-in";

let colorGenerator = () => {
  let letters = "0123456789ABCDEF";
  let color = '#';

  for(let i = 0; i < 6; i++){
    color += letters[Math.floor(Math.random() * 16)];
  }
  return color
}

btn.addEventListener("click", () => {
  let body = document.body;
  let randomColor = colorGenerator();
  
  const dadJokes = generateDadJokes();
  jokeDisplay.style.opacity = 0;

  setTimeout(() => {
    jokeDisplay.innerHTML = "&ldquo;" + dadJokes + "&rdquo;";
    jokeDisplay.style.opacity = 1;
  }, 500);

  body.style.backgroundColor = randomColor;

});
